---
root_password_encrypted:
    "$1$bLPNN09I$miuAa4ZBoeP3Y7cUYB5LC/"

name_servers:
    - 192.168.168.13
    - 8.8.4.4

ntp:
    boot_server: 192.168.168.13
    servers:
        - 192.168.168.13

radius:
    - server_ip: 192.168.168.13
      secret_encrypted: "$9$sDYJGTQ36/tgon9puhcKM87VskqfFnCz3"

auth_order:
    radius
    password

login_class:
    - name: Administrator
      idle: 10
      perm:
          view
          network
          system
    - name: RO
      idle: 5
      perm:
          view
          network
        
users:
    - name: remote-admin
      full_name: '"Template for full-admin RADIUS users"'
      uid: 9001
      class: super-user

local_services:
    - ssh
    - netconf_ssh

syslog:
    loggers:
        - type: user
          name: "*"
          fac_sev:
              - "any emergency"
        - type: file
          name: messages
          fac_sev:
              - "any notice"
              - "authorization info"
        - type: file
          name: interactive-commands
          fac_sev:
              - "interactive-commands any"
        - type: host
          name_ip: 192.168.100.110
          fac_sev:
              - "any info"
    file_size: 1m
    num_files: 10

snmp:
    client_lists:
        - name: GREG-NET
          clients:
            - 192.168.168.102/32
    communities:
        - name: greg-net
          auth: read-only

mgt_net:
    prefix: 192.168.0.0/16
    nh: 192.168.100.1

