groups {
    /* These system{} configs are intended for Qfabirc */
    SYSTEM_BASICS {
        system {
            authentication-order [ {{ auth_order }} ];
            host-name {{ my_host_name }};
            domain-name {{ my_domain_name }};
            time-zone {{ local_timezone }};
            root-authentication {
                encrypted-password {{ root_password_encrypted }};
            }
            name-server {
{% for server in name_servers %}
                {{ server }};
{% endfor %}
            }
            radius-server {
{% for server in radius %}
                {{ server.server_ip }} {
                    secret {{ server.secret_encrypted }};
                }
{% endfor %}
            }
            login {
{% for class in login_class %}
                class {{ class.name }} {
                    idle-timeout {{ class.idle }};
                    permissions [ {{ class.perm }} ];
                }
{% endfor %}
{% for user in users %}
                user {{ user.name }} {
                    full-name {{ user.full_name }};
                    uid {{ user.uid }};
                    class {{ user.class }};
                }
{% endfor %}
            }
            services {
{% for service in local_services %}
{% if service == 'netconf_ssh' %}
                netconf {
                    ssh;
                }
{% else %}
                {{ service }};
{% endif %}
{% endfor %}
            }
            syslog {
{% for logger in syslog.loggers %}
{% if logger.type == 'user' %}
                user {{ logger.name }} {
{% elif logger.type == 'file' %}
                file {{ logger.name }} {
{% elif logger.type == 'host' %}
                host {{ logger.name_ip }} {
                    log-prefix {{ syslog_prefix }};
{% endif %}
{% for facility in logger.fac_sev %}
                    {{ facility }};
{% endfor %}
                }
{% endfor %}
                archive size {{ syslog.file_size }} files {{ syslog.num_files }};
            }
            ntp {
                boot-server {{ ntp.boot_server }};
{% for server in ntp.servers %}
                server {{ server }};
{% endfor %}
            }
        }
        snmp {
{% for list in snmp.client_lists %}
            client-list {{ list.name }} {
{% for client in list.clients %}
                {{ client }};
{% endfor %}
            }
{% endfor %}
{% for community in snmp.communities %}
            community {{ community.name }} {
                authorization {{ community.auth }};
            }
{% endfor %}
        }
        policy-options {
            prefix-list MGT-NETS {
                {{ mgt_net.prefix }};
            }
            prefix-list SNMP-SERVERS {
                apply-path "snmp client-list <*> <*>";
            }
            prefix-list BGP-PEERS {
                apply-path "protocols bgp group <*> neighbor <*>";
            }
        }
    }
}
apply-groups SYSTEM_BASICS;
