---
# =========================================================
# Setup variables and directories
# =========================================================

- name: Creating build directories for each host
  hosts: vpls
  connection: local
  gather_facts: no
  tasks:
    - set_fact:
        build_dir: "{{ build_dir }}/{{ inventory_hostname }}/tmp"
        junos_conf: "{{ build_dir }}/{{ inventory_hostname}}/vpls.conf"
    - name: remove host build temp directory
      file: path={{ build_dir }} state=absent
    - name: create host build temp directory
      file: path={{ build_dir }} state=directory

# =========================================================
# Role based config template building
# =========================================================

- name: Build VPLS config on Junos routing platforms
  hosts: vpls
  connection: local
  gather_facts: no
  roles:
    - vpls_instance

